### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by ogrosko** [ebdrup/html2pdf.it#45]
When I run my server I get following error:

> Something broke!

In console I get

`Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1169:11)
    at exports.spawn (child_process.js:999:9)
    at generatePdf (/var/zpanel/hostdata/zadmin/public_html/html2pdf/lib/webservices/pdf.js:85:22)
    at Request._callback (/var/zpanel/hostdata/zadmin/public_html//html2pdf/lib/webservices/pdf.js:68:4)
    at Request.self.callback (/var/zpanel/hostdata/zadmin/public_html/html2pdf/node_modules/request/request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/var/zpanel/hostdata/zadmin/public_html/html2pdf/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/var/zpanel/hostdata/zadmin/public_html/html2pdf/node_modules/request/request.js:1187:12)
::ffff:178.143.102.198 - - [29/Mar/2016:11:36:48 +0000] "GET /?url=mu-url%3A8080&download=false&format=A4&downloadToken=1459251408405&orientation=portrait&margin=1cm HTTP/1.1" 500 16 "http:/my-url:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
`

Do you have any idea where could be the problem?

**Comment by ebdrup** [comment]
try the latest version
